### ISSUE TITLE
Cards in discard pile and faded when they should be in not in the discard pile

### ISSUE THREAD

**Issue by timotree3** [Hanabi-Live/hanabi-live#1704] opened 2020-08-28 01:26 UTC
![Screenshot from 2020-08-27 21-21-14](https://user-images.githubusercontent.com/6473438/91510671-c3305e00-e8ab-11ea-90d4-e18b1b9851d4.png)

https://hanab.live/replay/282225 working on steps to reproduce

**Comment by timotree3** [comment] 2020-08-28 05:10
well what happened the first time was that we were on turn 35 or so and then jumped to turn 28 and these cards that were in the discard pile on 35 but weren't yet discarded on 28 became faded instead of disappearing like they should've. I can't reproduce it.

**Comment by Zamiell** [comment] 2020-08-28 14:35
well

* `setFade()` function is called in 1 place: `setStatus() function
* `setStatus()` function is called in 2 places:
  * `onCardStatusChanged()` function, which is called when `globals.state.cardStatus` changes
  * `setBareImage()` function, which is caled in the `updateCardVisuals()` function (and other unimportant places), which is called here:
```
  // Card visuals
  subFullState((s) => {
    const card = s.visibleState!.deck[order];
    return {
      rank: card.rank,
      suitIndex: card.suitIndex,
      location: card.location,
      suitDetermined: card.suitDetermined,
      rankDetermined: card.rankDetermined,
      identity: s.cardIdentities[order],
    };
```
so location should updated when it moves to discard pile

**Comment by Zamiell** [comment] 2020-08-28 14:38
@rob this is annoying because i thought that using a reactive model would prevent these kind of race-condition errors

**Comment by timotree3** [comment] 2020-08-28 21:40
note that these cards shouldn't be in the discard pile at all. the replay was rewound to a point before the faded cards were discarded

**Comment by Zamiell** [comment] 2020-08-28 21:41
oh so the bug is that they are drawn in the wrong location rather than that they are faded?

**Comment by timotree3** [comment] 2020-08-28 21:42
right I guess so

**Comment by Zamiell** [comment] 2020-08-28 21:42
sounds like you should rename the title of this issue to actually be accurate then

**Comment by Zamiell** [comment] 2020-12-04 02:38
should we close this if you can't reproduce it?

**Closed** 2022-02-01 20:51 UTC
