### ISSUE TITLE
flashing notes on stacks

### ISSUE THREAD

**Issue by Aigul9** [Hanabi-Live/hanabi-live#2229] opened 2021-07-26 20:53 UTC
https://user-images.githubusercontent.com/46625461/127057287-bdeed4a3-d5b1-4e53-8031-05f1ab025630.mp4
it feels like not all suits are affected

**Comment by Zamiell** [comment] 2021-12-12 13:39
does this still happen?

**Comment by Aigul9** [comment] 2021-12-12 16:35
yes

**Comment by Aigul9** [comment] 2021-12-12 16:35
on light pink here: https://hanab.live/shared-replay/675563#58

**Comment by Zamiell** [comment] 2021-12-12 16:38
doesn't happen for me

**Comment by Aigul9** [comment] 2021-12-12 16:41
i am using 75% scaling

**Comment by Zamiell** [comment] 2021-12-12 16:41
doesn't happen for me using 75% scaling

**Comment by Aigul9** [comment] 2021-12-12 16:50
i think it happends when tooltips are multidirectiona
![2021-12-12_19-48-56](https://user-images.githubusercontent.com/46625461/145721464-4c0e2209-3902-46d2-a7ac-54488d91f762.png)
![2021-12-12_19-49-08](https://user-images.githubusercontent.com/46625461/145721467-25cce0d8-2ff0-4fe4-9cf9-8f73bc3ac820.png)

l

**Comment by Zamiell** [comment] 2022-01-04 20:17
can you stop closing an reopening issues? it spams my notifications

**Comment by Aigul9** [comment] 2022-01-05 01:01
turn them off

**Comment by Zamiell** [comment] 2022-01-05 01:18
turn what off, my github notifications?

**Comment by Aigul9** [comment] 2022-01-05 11:27
your github notifications

**Comment by Aigul9** [comment] 2022-01-05 21:01
can you stop complaining that you received 4 extra notifications?

**Comment by vEnhance** [comment] 2022-11-10 12:11
Closing since can't reproduce either

**Closed by vEnhance** 2022-11-10 12:11 UTC
