### ISSUE TITLE
clues in hypo should never touched drawn blank cards

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2681] opened 2022-10-06 15:40 UTC

**Comment by Krycke** [comment] 2022-11-30 18:38
They touch them with negative information. This is also done with hidden cards in your own hand in an ongoing game.
Reproduce:
1. Start a new game. 
2. Set a note of y2 on one of your cards.
3. Enter Hypo and give yourself a yellow clue.
4. Now all other cards in your hand have negative yellow on them

**Comment by Zamiell** [comment] 2022-11-30 19:15
yeah, they should "touch" them with negative information

this issue is just about the clue arrows showing up on the clue preview mode / after the clue has been given
(in a hypothetical)

**Comment by Krycke** [comment] 2022-11-30 19:16
We don't know anything about the other cards, we don't know if the negative information is correct.

**Comment by Zamiell** [comment] 2022-11-30 19:18
huh

**Comment by Krycke** [comment] 2022-11-30 19:22
First, I can't reproduce your original bug. I can't get the arrows to appear on hidden cards.

Secondly, If the cards are hidden, we don't know what they are right. They can be b1. By cluing blue to Bob on a visible b4 (from a note or morph), the hidden b1 will get negative blue on it. But this of course is not correct.

**Comment by Zamiell** [comment] 2022-11-30 19:24
> Secondly, If the cards are hidden, we don't know what they are right. They can be b1. By cluing blue to Bob on a visible b4 (from a note or morph), the hidden b1 will get negative blue on it. But this of course is not correct.

then it sounds like we need to make a pr that includes code that says:

```ts
function applyNegativeClue(card) {
  // Early return
  if (cardIsMorphedBlank) {
    return;
  }
  
  // Rest of normal code
}
```

**Comment by Zamiell** [comment] 2022-11-30 19:25
> First, I can't reproduce your original bug.

i partially fixed it in this commit https://github.com/Hanabi-Live/hanabi-live/commit/6cdc7d32e206f89b99fefaf69ce2eb2b6c49b0d5

but i think it still happens with clue previews now, which i will try to verify later

**Comment by Zamiell** [comment] 2022-11-30 19:31
oh right, you need negative clues to apply to blank cards so that the checkbox works properly

**Comment by Krycke** [comment] 2022-11-30 19:34
Well I guess it's a mess in general, either you apply the information on the hidden cards, but then they won't be hidden properly because you could just try to clue colors and numbers to see which card it is. Or you don't give any information on hidden cards (positivt nor negative) but then if you show the hidden cards later, the information will be incorrect.

**Comment by Zamiell** [comment] 2022-11-30 19:36
> but then they won't be hidden properly because you could just try to clue colors and numbers to see which card it is

that's trivial to fix, just have an early return if the card is morphed blank

**Comment by Zamiell** [comment] 2023-01-11 13:50
does this still happen in clue previews?

**Comment by Krycke** [comment] 2023-01-11 14:03
This is how it is now.
1. Alice hand is <r1 r1 r1 r2 r2>
2. Enter Hypo as Alice
3. Discard slot 5
4. Alice hand is now <blank r1 r1 r1 r2>
5. Bob can't clue Alice, since all cards are hidden
6. Morph slot 3 into g1 (As of now, this works and we see g1 in slot 3)
7. Enter the clue 1 to Alice
8. The clue preview will only mark the visible g1
9. Commit to the clue, the arrows will show up on slot 2, 3 and 4, giving negative 1 on slot 1 and 5 (not visible on slot 1)
10. Click "show hidden cards" 
11. If Alice card on slot 1 is b1, this will now have negative 1 on it

If we change the behavior to
9. Commit to the clue, the arrow will show up on slot 3, g1, not giving neither negative nor positive information to the other slots
10. Click "Show hidden cards"
11. Non of Alice's cards except slot 3 were affected by the previous clue

**Comment by Zamiell** [comment] 2023-01-11 14:04
![image](https://user-images.githubusercontent.com/5511220/211826142-ce08ecee-b65f-4e08-a422-173417e4eaf2.png)

looks like your message got clipped

**Comment by Krycke** [comment] 2023-01-11 14:06
There

**Comment by Zamiell** [comment] 2023-01-11 14:07
> 5. Bob can't clue Alice, since all cards are hidden

Bob can clue Alice color red, number 1, and number 2.
right?

**Comment by Krycke** [comment] 2023-01-11 14:12
Not with Alice's cards hidden, no.
With her cards visible then there is no blank cards either.

With cards hidden, and after bob has drawn a card (which then is displayed blank), a clue given by alice will not have a preview allow over the blank card, but will give it negative information.

**Comment by Zamiell** [comment] 2023-01-11 14:51
to start with how about we just make clues work if they touch normal cards that are not hidden

**Comment by Krycke** [comment] 2023-01-11 15:46
Does that mean that Bob should be able to clue Alice 1, 2 and red on point 5? Or as it work now, but that the blank cards should not get any negative information?

**Comment by Zamiell** [comment] 2023-01-11 15:49
> Does that mean that Bob should be able to clue Alice 1, 2 and red on point 5?

yes, precisely

i don't care about positive or negative information right now, but ultimately i think the card should be clued like it was its real identity so that the checkbox works properly after cluing people

**Comment by Krycke** [comment] 2023-01-11 19:14
So just to make this clear, is you start the hypo on Alice, you don't see Alice's cards. You discard and it's bob's turn. You still don't see any of Alice's cards, and slot 1 is blank.

Now Bob should be able to clue Alice anything that he could clue Alice as if he saw her cards, and there should be a preview arrows over her cards even though the cards are hidden. And when you give the clue, the cards should actually be clued as if we saw the cards. Except the blank card, that should be completely ignored by the clue?

Is that correct?

**Comment by Zamiell** [comment] 2023-01-11 19:15
no

**Comment by Zamiell** [comment] 2023-01-11 19:15
i misunderstood that you were representing the cards as being hidden

**Comment by Zamiell** [comment] 2023-01-11 19:19
rewinding a bit:

> 9. Commit to the clue, the arrows will show up on slot 2, 3 and 4, giving negative 1 on slot 1 and 5 (not visible on slot 1)

yes, this is the bug.

> If we change the behavior to
9. Commit to the clue, the arrow will show up on slot 3, g1, not giving neither negative nor positive information to the other slots
10. Click "Show hidden cards"
11. Non of Alice's cards except slot 3 were affected by the previous clue

yes, that's fine for a first pass to fix the bug.

a more complicated and final solution should probably be that negative nor positive information is retroactively given to the slots based on the clues that were given.

**Comment by Krycke** [comment] 2023-01-11 19:21
If the cards are visible, then everything is as normal. All cards are getting the normal treatment. It's only when cards are being hidden that we get a strange behaviour. So in the case explain by the points above. Alice's cards are hidden. Nothing can be clued. We morph one card, that card can be clued. We do that.

Now, 
1. what should happen to the other cards in alices hand, that should be targeted by the clue but are hidden.
2. What should happen to the cards that should not be targeted, but are hidden.
3. What should happen to the blank cards in alices hand that might be or not be affected by the clue?

**Comment by Krycke** [comment] 2023-01-11 19:25
And i guess in the final solution, if you hide cards again, then the cards should be hidden with the new updated information applied.

**Comment by Zamiell** [comment] 2023-01-11 19:33
> what should happen to the other cards in alices hand, that should be targeted by the clue but are hidden.

by this i assume you mean non-blank cards with partial information, e.g. a 3 with a number clue on it but without any color filed in.
i think they should get the clues applied, but still remain in their same state until the checkbox is checked.
if that is too difficult, then don't bother and just don't apply the clues at all.

> What should happen to the cards that should not be targeted, but are hidden.

i dont know what you mean by this

> What should happen to the blank cards in alices hand that might be or not be affected by the clue?

by this i assume you mean a drawn card that is in the blank state.
i think they should get the clues applied, but still remain in their same state until the checkbox is checked.
if that is too difficult, then don't bother and just don't apply the clues at all.

**Closed** 2023-01-13 21:17 UTC
Labels: bug
